name: Deploy Job Search
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # load custom action here
      - name: Load & Cache dependencies
        uses: ./.github/actions/dependencies-cache
        with:
          caching: false
      - name: Output Information
        run : echo "Cache used? ${{ steps.dependencies-cache.outputs.used-cache }}"
      - name: Lint Code base
        run : npm run lint
  test:
      needs: ["lint"]
      runs-on: ubuntu-latest
      steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/dependencies-cache
      - name: Run test
        continue-on-error: true # run other jobs even if this job fails
        id: test-run
        run: npm run test:unit
      - name: Upload test report
        if: failure() && steps.test-run.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
